### ISSUE TITLE
Calling set on destroyed object in acceptance tests

### ISSUE THREAD

**Issue by bilherron** [topaxi/ember-img-lazy#1]
I added this add-on to an application of mine and when tests are run I am getting errors `calling set on destroyed object` in the `preloadImage` function and `Cannot read property 'element' of undefined` in the `unobserve` function.

I'm not sure if the problem is with my code or if there should be some defensive checks in the add-on. I created a fork that [solved the problem for me](https://github.com/bilherron/ember-img-lazy/commit/586e564366e46ff92149ff5d17bbc8b5bd9f131a) but I didn't want to send a PR if the issue was really with my application code.

Any ideas on this? Thanks!

**Comment by topaxi** [comment]
Yes this is probably caused by the addon, happy to accept your PR. Haven't had time to use is in an acceptance test yet :)

**Comment by topaxi** [comment]
Thanks for reporting and fixing this! :heart:
