### ISSUE TITLE
Broken in ember 3.1

### ISSUE THREAD

**Issue by RobbieTheWagner** [topaxi/ember-img-lazy#3]
It throws:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.get (<anonymous>)
    at Object.get (core_object.js:52)
    at getOwner (ember-utils.js:290)
    at Proxy.<anonymous> (config.js:13)
    at ComputedPropertyPrototype.get (ember-metal.js:4061)
    at get (ember-metal.js:3438)
    at _getPath (ember-metal.js:3462)
    at get (ember-metal.js:3445)
    at Proxy.unknownProperty (config.js:17)
    at Object.get (core_object.js:55)
```

**Comment by topaxi** [comment]
Hi, I could fix this specific error, as I was trying to assign a property which was an injected service 😱 
Anyway, `ember-beta` and `ember-canary` still won't work just yet, I haven't had enough time yet to fix it.

https://travis-ci.org/topaxi/ember-img-lazy/jobs/343258181

Might be related to the `ember-config-service` addon I'm using, which in turn uses `ember-getowner-polyfill` which shouldn't be necessary for newer Ember versions anyways.

**Comment by RobbieTheWagner** [comment]
Hi @topaxi! Yeah, it looks like the config service uses `factoryFor` which I think has been deprecated. I generally use https://github.com/patience-tema-baron/ember-get-config or the normal method that they suggest in their README of `const config = Ember.getOwner(this).resolveRegistration('config:environment');`. Please let me know if you'd like me to try these out here.

**Comment by topaxi** [comment]
Uh I like this addon a lot, very minimal and exactly what we need! I'd be happy to accept a PR replacing the old one with `ember-get-config`!

**Comment by dudv** [comment]
@topaxi Thanks for the nice addon. Could you please merge in #4 to make it work with ember 3.2?
